### PR TITLE
Item updates

### PR DESCRIPTION
**Pull request by DabirSA**
Fully updates My Room goods names, Mag evo device names and descriptions, accessory names and descriptions.
Standardises accessory ticket line breaks to bring the first 12,000 of them in line with everything else that uses this kind of description.
Changes mag evo device description format to bring it down to 2 lines.
Replaces full-width asterisks with normal asterisks in weapon camo description names.
Translates names and descriptions of a hell of a lot of item sets. 374 still need names translating, 130 need descriptions; it was over 3000 last week. All remaining descriptions are unreleased sets.
Translations and tweaks for a few cosmetics and room good descriptions.

### CODE REVIEW

**Comment by alama** [comment]
Why did you changed `＊` to `*` ?

**Comment by DabirSA** [comment]
There's no functional difference between `＊` and `*` except that one is a Japanese character in English names. They're interchangeable in in-game searches and they render the same. I changed it for the same reason that you wouldn't have `Ｂ` in english names even if it works and looks the same.

**Comment by alama** [comment]
Well, the normalize script that keep the text format, well, unicode normalized is output a LARGE diff https://8-113946707-gh.circle-artifacts.com/0/Reports/normalize.dif

**Comment by DabirSA** [comment]
So it automatically changes it back or something?

**Comment by SynthSy** [comment]
Do not change the asterisks please, there's a difference on our end.

**Pull request merged**
