### PR TITLE
Changed "More" to "Clay"

### PR DESCRIPTION
**Pull request by SynthSy**

### CODE REVIEW

**Comment by PolCPP** [comment]
Clay...more, is that a pun?

**Comment by SynthSy** [comment]
Possibly.

**Comment by dot-Hacker** [comment]
not sure if my comment showed up on story commit; moore is the proper english spelling in-line with the japanese script, however, i sure like clay better. Inb4 weeaboo comments "but it's more!"

**Comment by SynthSy** [comment]
I know about the weaponoids. And I took your opinion into the matter and I ended up going with Clay, since it still works, although we'll likely get comments about it, but that's unavoidable at some point.

Most of the dialog in the UI had to be reworded due to the character limit and how weird it sounds in english, which people may not understand.

**Comment by dot-Hacker** [comment]
10-4
the latter part was my concern. do you know the limits per box / heading ? i am 100% on board with liberal not literal translations, as seen in my main game work.

**Comment by SynthSy** [comment]
It seems to be around 17-20 character limit per line. Though I know it varies per device DPI.

**Pull request merged**
